baseURL = "http://www.matfys.lth.se/staff/Andrea.Idini/"
languageCode = "en-gb"
title = "Andrea Idini"

theme = "Idini"

uglyURLs  = true
canonifyURLs = true

[taxonomies]
  tags = "idini"
  category = "Personal Website"

[outputFormats.HTML]
  nougly = true
