baseURL = "http://www.matfys.lth.se/staff/Andrea.Idini/"
languageCode = "en-gb"
title = "Andrea Idini"

theme = "Idini"

uglyURLs  = true
canonifyURLs = true

[taxonomies]
  tags = ["idini", "andrea", "professor", "mathematical", "physics", nuclear"]
  category = "Personal Website"

[outputFormats.HTML]
  nougly = true
