baseURL = "https://mywebby/"
languageCode = "en-gb"
title = "Andrea Idini"

theme = "Idini"

uglyURLs  = true
canonifyURLs = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputFormats.HTML]
  nougly = true