baseURL = "http://www.matfys.lth.se/staff/Andrea.Idini/"
languageCode = "en-gb"
title = "Andrea Idini"

theme = "Idini"

uglyURLs  = true
canonifyURLs = true

[taxonomies]
  tag = "tag"
  category = "categories"

[outputFormats.HTML]
  nougly = true
